#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM ecs_combo[] = {KC_W, KC_E, COMBO_END};
const uint16_t PROGMEM tab_combo[] = {KC_S, KC_D, COMBO_END};
const uint16_t PROGMEM bspc_combo[] = {KC_I, KC_O, COMBO_END};
const uint16_t PROGMEM ent_combo[] = {KC_K, KC_L, COMBO_END};
combo_t key_combos[] = {
    COMBO(ecs_combo, KC_ESC),
    COMBO(tab_combo, KC_TAB),
    COMBO(bspc_combo, KC_BSPC),
    COMBO(ent_combo, KC_ENT),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_4x12
        (
        KC_Q,         KC_W,    KC_E,    KC_R,         KC_T,    KC_Y,    KC_U,         KC_I,    KC_O,     KC_P,            KC_MINS, KC_EQL,
        LT(2,KC_A),   KC_S,    KC_D,    KC_F,         KC_G,    KC_H,    KC_J,         KC_K,    KC_L,     LT(3,KC_SCLN),   KC_QUOT, KC_VOLU,
        LSFT_T(KC_Z), KC_X,    KC_C,    KC_V,         KC_B,    KC_N,    KC_M,         KC_COMM, KC_DOT,   RSFT_T(KC_SLSH), KC_UP,   KC_VOLD,
        KC_CAPS,      KC_LCTL, KC_LGUI, KC_SPC,       MO(1),   MO(2),  KC_SPC,        KC_RGUI, KC_RALT,  KC_LEFT,         KC_DOWN, KC_RIGHT
        ),
    [1] = LAYOUT_ortho_4x12
        (
        KC_1,         KC_2,    KC_3,    KC_4,         KC_5,    KC_6,    KC_7,         KC_8,    KC_9,     KC_0,           XXXXXXX, XXXXXXX,
        KC_GRV,       XXXXXXX, XXXXXXX, KC_VOLU,      XXXXXXX, KC_PGUP, KC_MINS,      KC_EQL,  KC_PGDN,  KC_QUOT,        XXXXXXX, XXXXXXX,
        KC_LSFT,      KC_DEL,  XXXXXXX, KC_VOLD,      XXXXXXX, XXXXXXX, XXXXXXX,      KC_LBRC, KC_RBRC,  RSFT_T(KC_BSLS),XXXXXXX, XXXXXXX,
        _______,      KC_LCTL, KC_LGUI, KC_SPC,       _______, MO(4),   KC_SPC,       KC_RGUI, KC_RALT,  XXXXXXX,        XXXXXXX, XXXXXXX
        ),
    [2] = LAYOUT_ortho_4x12
        (
        KC_EXLM,      KC_AT,   KC_HASH, KC_DLR,       KC_PERC, KC_CIRC, KC_AMPR,      KC_ASTR, KC_LPRN,  KC_RPRN,         XXXXXXX, XXXXXXX,
        KC_TILD,      XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, KC_HOME, KC_UNDS,      KC_PLUS, KC_END,   KC_DQUO,         XXXXXXX, XXXXXXX,
        KC_LSFT,      XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,      KC_LCBR, KC_RCBR,  KRSFT_T(KC_PIPE), XXXXXXX, XXXXXXX,
        _______,      KC_LCTL, KC_LGUI, KC_SPC,       MO(4),   _______,  KC_SPC,      KC_RGUI, KC_RALT,  XXXXXXX,         XXXXXXX, XXXXXXX
        ),
    [3] = LAYOUT_ortho_4x12
        (
        KC_F1,        KC_F2,   KC_F3,   KC_F4,        KC_F5,   KC_F6,   KC_F7,        KC_F8,   KC_F9,    KC_F10,          XXXXXXX, XXXXXXX,
        KC_CAPS,      XXXXXXX, XXXXXXX, XXXXXXX,      RGB_TOG, KC_LEFT, KC_DOWN,      KC_UP,   KC_RIGHT, _______,         XXXXXXX, XXXXXXX,
        KC_LSFT,      XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,      KC_F11,  KC_F12,   KC_RSFT,         XXXXXXX, XXXXXXX,
        _______,      KC_LCTL, KC_LGUI, KC_SPC,       XXXXXXX, XXXXXXX,  KC_SPC,      KC_RGUI, KC_RALT,  XXXXXXX,         XXXXXXX, XXXXXXX
        ),
    [4] = LAYOUT_ortho_4x12
        (
        XXXXXXX,      XXXXXXX, MS_UP,   XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,  XXXXXXX,         XXXXXXX, XXXXXXX,
        XXXXXXX,      MS_LEFT, MS_DOWN, MS_RGHT,      XXXXXXX, MS_BTN1, MS_WHLD,      MS_WHLU, MS_BTN2,  XXXXXXX,         XXXXXXX, XXXXXXX,
        KC_LSFT,      XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,  KC_RSFT,         XXXXXXX, XXXXXXX,
        _______,      KC_LCTL, KC_LGUI, KC_SPC,       XXXXXXX, XXXXXXX,  KC_SPC,      KC_RGUI, KC_RALT,  XXXXXXX,         XXXXXXX, XXXXXXX
        )
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


